import Vue from 'vue'
import { Button, Input, Form, FormItem, Tabs, TabPane, Message, Container, Header, Aside, Main, Icon, Row, Col, Select, Option, Menu, Submenu, MenuItem, MenuItemGroup, Collapse, CollapseItem, Card, Table, TableColumn, Upload } from 'element-ui'

Vue.use(Button)
Vue.use(Input)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.component(Message)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Icon)
Vue.use(Row)
Vue.use(Col)
Vue.use(Select)
Vue.use(Option)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Card)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Upload)

Vue.prototype.$message = Message
